### PR TITLE
Explicitly require setuptools >=8.0 (resolves #1323)

### LINKED ISSUE #1323: setuptools 8.0.0 or later is now required for PEP 440 version support
python 2.7.9
setuptools 5.5.1
```
Traceback (most recent call last):
  File "version_template.py", line 137, in <module>
    _main()
  File "version_template.py", line 133, in _main
    sys.stdout.write(expand_(*sys.argv[1:]))
  File "version_template.py", line 128, in expand_
    return resolve(name)
  File "version_template.py", line 122, in resolve
    v = v()
  File "version_template.py", line 61, in distVersion
    if build_number is not None and parse_version(baseVersion).is_prerelease:
AttributeError: 'tuple' object has no attribute 'is_prerelease'
```

### PR DESCRIPTION
**Pull request by hannes-ucsc**
Resolves #1323

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Build failure tracked in #1093, merging.
